/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.pat2022.UI;

/**
 *
 * @author Murrayy
 */
public class MoreInfoScreen extends javax.swing.JFrame {

    /**
     * Creates new form MoreInfoScreen
     */
    public MoreInfoScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MoreInfoLabel = new javax.swing.JLabel();
        SubjectLabel = new javax.swing.JLabel();
        SubjectTextField = new javax.swing.JTextField();
        DetailsLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        DetailsTextArea = new javax.swing.JTextArea();
        MarksLabel = new javax.swing.JLabel();
        MarksTextField = new javax.swing.JTextField();
        DateDueLabel = new javax.swing.JLabel();
        DateDueTextField = new javax.swing.JTextField();
        MarksRecievedLabel = new javax.swing.JLabel();
        MarksRecievedTextField = new javax.swing.JTextField();
        BackButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MoreInfoLabel.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        MoreInfoLabel.setText("MORE INFO");

        SubjectLabel.setFont(new java.awt.Font("Candara", 1, 12)); // NOI18N
        SubjectLabel.setText("SUBJECT:");

        SubjectTextField.setEditable(false);
        SubjectTextField.setFont(new java.awt.Font("Candara", 1, 12)); // NOI18N

        DetailsLabel.setFont(new java.awt.Font("Candara", 1, 12)); // NOI18N
        DetailsLabel.setText("DETAILS: ");

        DetailsTextArea.setColumns(20);
        DetailsTextArea.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        DetailsTextArea.setRows(5);
        jScrollPane1.setViewportView(DetailsTextArea);

        MarksLabel.setFont(new java.awt.Font("Candara", 1, 12)); // NOI18N
        MarksLabel.setText("MARKS:");

        MarksTextField.setEditable(false);
        MarksTextField.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        MarksTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MarksTextFieldActionPerformed(evt);
            }
        });

        DateDueLabel.setFont(new java.awt.Font("Candara", 1, 12)); // NOI18N
        DateDueLabel.setText("DATE DUE: ");

        DateDueTextField.setEditable(false);
        DateDueTextField.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        DateDueTextField.setText(" ");

        MarksRecievedLabel.setFont(new java.awt.Font("Candara", 1, 12)); // NOI18N
        MarksRecievedLabel.setText("MARKS RECIEVED: ");

        MarksRecievedTextField.setEditable(false);
        MarksRecievedTextField.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N

        BackButton.setFont(new java.awt.Font("Candara", 1, 12)); // NOI18N
        BackButton.setText("BACK");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MoreInfoLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(DateDueLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                            .addComponent(MarksLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DetailsLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SubjectLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(SubjectTextField)
                            .addComponent(MarksTextField)
                            .addComponent(DateDueTextField))
                        .addGap(95, 95, 95)
                        .addComponent(MarksRecievedLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MarksRecievedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(BackButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MoreInfoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SubjectLabel)
                    .addComponent(SubjectTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MarksRecievedLabel)
                    .addComponent(MarksRecievedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DetailsLabel)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MarksLabel)
                    .addComponent(MarksTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DateDueLabel)
                    .addComponent(DateDueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(BackButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MarksTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MarksTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MarksTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MoreInfoScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MoreInfoScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MoreInfoScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MoreInfoScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MoreInfoScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JLabel DateDueLabel;
    private javax.swing.JTextField DateDueTextField;
    private javax.swing.JLabel DetailsLabel;
    private javax.swing.JTextArea DetailsTextArea;
    private javax.swing.JLabel MarksLabel;
    private javax.swing.JLabel MarksRecievedLabel;
    private javax.swing.JTextField MarksRecievedTextField;
    private javax.swing.JTextField MarksTextField;
    private javax.swing.JLabel MoreInfoLabel;
    private javax.swing.JLabel SubjectLabel;
    private javax.swing.JTextField SubjectTextField;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
