/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.pat2022.UI;

/**
 *
 * @author Murrayy
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPane = new javax.swing.JTabbedPane();
        HomePanel = new javax.swing.JPanel();
        mainScreenLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        UpcomingAssignmentList = new javax.swing.JList<>();
        MarkDoneButton = new javax.swing.JButton();
        ViewInfoButton = new javax.swing.JButton();
        DateLabel = new javax.swing.JLabel();
        jScrollPane14 = new javax.swing.JScrollPane();
        DateArea = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        SubjectPanel = new javax.swing.JPanel();
        SubjectsLabel = new javax.swing.JLabel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        SubjectPanel1 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        UpcomingSubjectList1 = new javax.swing.JList<>();
        NewAssignmentButton1 = new javax.swing.JButton();
        jScrollPane12 = new javax.swing.JScrollPane();
        MarkArea1 = new javax.swing.JTextArea();
        MarkLabel1 = new javax.swing.JLabel();
        SubjectPanel2 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        UpcomingSubjectList2 = new javax.swing.JList<>();
        NewAssigmentButton2 = new javax.swing.JButton();
        jScrollPane13 = new javax.swing.JScrollPane();
        MarkArea2 = new javax.swing.JTextArea();
        MarkLabel2 = new javax.swing.JLabel();
        SubjectPanel3 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        UpcomingSubjectList3 = new javax.swing.JList<>();
        newAssignmentButton3 = new javax.swing.JButton();
        MarkLabel3 = new javax.swing.JLabel();
        jScrollPane19 = new javax.swing.JScrollPane();
        MarkArea3 = new javax.swing.JTextArea();
        SubjectPanel4 = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        UpcomingSubjectList4 = new javax.swing.JList<>();
        NewAssignmentButton4 = new javax.swing.JButton();
        MarkLabel4 = new javax.swing.JLabel();
        jScrollPane20 = new javax.swing.JScrollPane();
        MarkArea4 = new javax.swing.JTextArea();
        SubjectPanel5 = new javax.swing.JPanel();
        jScrollPane9 = new javax.swing.JScrollPane();
        UpcomingSubjectList5 = new javax.swing.JList<>();
        NewAssignmentButton5 = new javax.swing.JButton();
        MarkLabel5 = new javax.swing.JLabel();
        jScrollPane21 = new javax.swing.JScrollPane();
        MarkArea5 = new javax.swing.JTextArea();
        SubjectPanel6 = new javax.swing.JPanel();
        jScrollPane10 = new javax.swing.JScrollPane();
        UpcomingSubjectList6 = new javax.swing.JList<>();
        NewAssignmentButton6 = new javax.swing.JButton();
        MarkLabel6 = new javax.swing.JLabel();
        jScrollPane22 = new javax.swing.JScrollPane();
        MarkArea6 = new javax.swing.JTextArea();
        SubjectPanel7 = new javax.swing.JPanel();
        jScrollPane11 = new javax.swing.JScrollPane();
        UpcomingSubjectList7 = new javax.swing.JList<>();
        NewAssignmentButton7 = new javax.swing.JButton();
        MarkLabel7 = new javax.swing.JLabel();
        jScrollPane23 = new javax.swing.JScrollPane();
        MarkArea7 = new javax.swing.JTextArea();
        AddSubjectButton = new javax.swing.JButton();
        RemoveSubjectButton = new javax.swing.JButton();
        TimeTablePanel = new javax.swing.JPanel();
        TimeTableLabel = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TimeTable = new javax.swing.JTable();
        AddEventButton = new javax.swing.JButton();
        RemoveEventButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        TermPanel = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        TermTable = new javax.swing.JTable();
        TermOverviewLabel = new javax.swing.JLabel();
        AddEventButton2 = new javax.swing.JButton();
        DeleteEventButton = new javax.swing.JButton();
        TasksDonePanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        CompletedList = new javax.swing.JList<>();
        TasksDoneLabel = new javax.swing.JLabel();
        ViewInfoButton2 = new javax.swing.JButton();
        DeleteButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MainPane.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 204, 255), 3, true));
        MainPane.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        MainPane.setFont(new java.awt.Font("Candara", 1, 12)); // NOI18N

        HomePanel.setBackground(new java.awt.Color(153, 204, 255));

        mainScreenLabel.setBackground(new java.awt.Color(204, 204, 204));
        mainScreenLabel.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        mainScreenLabel.setText("MAIN SCREEN");
        mainScreenLabel.setToolTipText("");

        UpcomingAssignmentList.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "UPCOMING: ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Candara", 0, 14), new java.awt.Color(102, 153, 255))); // NOI18N
        UpcomingAssignmentList.setFont(new java.awt.Font("Candara", 1, 12)); // NOI18N
        UpcomingAssignmentList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5", "Item 6 ", "Item 7", "Item 8", "Item 9", "Item 10" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(UpcomingAssignmentList);

        MarkDoneButton.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        MarkDoneButton.setText("MARK AS DONE");

        ViewInfoButton.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        ViewInfoButton.setText("VIEW INFO");

        DateLabel.setFont(new java.awt.Font("Candara", 1, 12)); // NOI18N
        DateLabel.setText("CURRENT DATE:");

        DateArea.setColumns(20);
        DateArea.setFont(new java.awt.Font("Candara", 1, 12)); // NOI18N
        DateArea.setRows(5);
        jScrollPane14.setViewportView(DateArea);

        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout HomePanelLayout = new javax.swing.GroupLayout(HomePanel);
        HomePanel.setLayout(HomePanelLayout);
        HomePanelLayout.setHorizontalGroup(
            HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mainScreenLabel)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MarkDoneButton)
                    .addComponent(ViewInfoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(HomePanelLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(DateLabel)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)))
                .addContainerGap(209, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HomePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(156, 156, 156))
        );
        HomePanelLayout.setVerticalGroup(
            HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomePanelLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(mainScreenLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DateLabel)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(MarkDoneButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ViewInfoButton)
                .addContainerGap())
        );

        MainPane.addTab("HOME", HomePanel);

        SubjectPanel.setBackground(new java.awt.Color(153, 204, 255));

        SubjectsLabel.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        SubjectsLabel.setText("SUBJECTS");

        jTabbedPane3.setFont(new java.awt.Font("Candara", 1, 12)); // NOI18N

        UpcomingSubjectList1.setBorder(javax.swing.BorderFactory.createTitledBorder("RELATED UPCOMING ASSIGNMENTS"));
        UpcomingSubjectList1.setFont(new java.awt.Font("Candara", 1, 12)); // NOI18N
        UpcomingSubjectList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane5.setViewportView(UpcomingSubjectList1);

        NewAssignmentButton1.setFont(new java.awt.Font("Candara", 1, 12)); // NOI18N
        NewAssignmentButton1.setText("CREATE NEW ASSIGNMENT");

        MarkArea1.setColumns(20);
        MarkArea1.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        MarkArea1.setRows(5);
        MarkArea1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 2, true));
        jScrollPane12.setViewportView(MarkArea1);

        MarkLabel1.setFont(new java.awt.Font("Candara", 1, 12)); // NOI18N
        MarkLabel1.setText("MARKS RECIEVED");

        javax.swing.GroupLayout SubjectPanel1Layout = new javax.swing.GroupLayout(SubjectPanel1);
        SubjectPanel1.setLayout(SubjectPanel1Layout);
        SubjectPanel1Layout.setHorizontalGroup(
            SubjectPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SubjectPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SubjectPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SubjectPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane5)
                        .addComponent(NewAssignmentButton1)
                        .addComponent(jScrollPane12, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE))
                    .addComponent(MarkLabel1))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        SubjectPanel1Layout.setVerticalGroup(
            SubjectPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SubjectPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(NewAssignmentButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(MarkLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane3.addTab("tab1", SubjectPanel1);

        UpcomingSubjectList2.setBorder(javax.swing.BorderFactory.createTitledBorder("RELATED UPCOMING ASSIGNMENTS"));
        UpcomingSubjectList2.setFont(new java.awt.Font("Candara", 1, 12)); // NOI18N
        UpcomingSubjectList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane6.setViewportView(UpcomingSubjectList2);

        NewAssigmentButton2.setFont(new java.awt.Font("Candara", 1, 12)); // NOI18N
        NewAssigmentButton2.setText("CREATE NEW ASSIGNMENT");

        MarkArea2.setColumns(20);
        MarkArea2.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        MarkArea2.setRows(5);
        MarkArea2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 2, true));
        jScrollPane13.setViewportView(MarkArea2);

        MarkLabel2.setFont(new java.awt.Font("Candara", 1, 12)); // NOI18N
        MarkLabel2.setText("MARKS RECIEVED");

        javax.swing.GroupLayout SubjectPanel2Layout = new javax.swing.GroupLayout(SubjectPanel2);
        SubjectPanel2.setLayout(SubjectPanel2Layout);
        SubjectPanel2Layout.setHorizontalGroup(
            SubjectPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SubjectPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SubjectPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SubjectPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE)
                        .addComponent(NewAssigmentButton2)
                        .addComponent(jScrollPane13))
                    .addComponent(MarkLabel2))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        SubjectPanel2Layout.setVerticalGroup(
            SubjectPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SubjectPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(NewAssigmentButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(MarkLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane3.addTab("tab2", SubjectPanel2);

        UpcomingSubjectList3.setBorder(javax.swing.BorderFactory.createTitledBorder("RELATED UPCOMING ASSIGNMENTS"));
        UpcomingSubjectList3.setFont(new java.awt.Font("Candara", 1, 12)); // NOI18N
        UpcomingSubjectList3.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane7.setViewportView(UpcomingSubjectList3);

        newAssignmentButton3.setFont(new java.awt.Font("Candara", 1, 12)); // NOI18N
        newAssignmentButton3.setText("CREATE NEW ASSIGNMENT");

        MarkLabel3.setFont(new java.awt.Font("Candara", 1, 12)); // NOI18N
        MarkLabel3.setText("MARKS RECIEVED");

        MarkArea3.setColumns(20);
        MarkArea3.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        MarkArea3.setRows(5);
        MarkArea3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 2, true));
        jScrollPane19.setViewportView(MarkArea3);

        javax.swing.GroupLayout SubjectPanel3Layout = new javax.swing.GroupLayout(SubjectPanel3);
        SubjectPanel3.setLayout(SubjectPanel3Layout);
        SubjectPanel3Layout.setHorizontalGroup(
            SubjectPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SubjectPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SubjectPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane19)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE)
                    .addComponent(newAssignmentButton3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MarkLabel3, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        SubjectPanel3Layout.setVerticalGroup(
            SubjectPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SubjectPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(newAssignmentButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(MarkLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane3.addTab("tab3", SubjectPanel3);

        UpcomingSubjectList4.setBorder(javax.swing.BorderFactory.createTitledBorder("RELATED UPCOMING ASSIGNMENTS"));
        UpcomingSubjectList4.setFont(new java.awt.Font("Candara", 1, 12)); // NOI18N
        UpcomingSubjectList4.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane8.setViewportView(UpcomingSubjectList4);

        NewAssignmentButton4.setFont(new java.awt.Font("Candara", 1, 12)); // NOI18N
        NewAssignmentButton4.setText("CREATE NEW ASSIGNMENT");

        MarkLabel4.setFont(new java.awt.Font("Candara", 1, 12)); // NOI18N
        MarkLabel4.setText("MARKS RECIEVED");

        MarkArea4.setColumns(20);
        MarkArea4.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        MarkArea4.setRows(5);
        MarkArea4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 2, true));
        jScrollPane20.setViewportView(MarkArea4);

        javax.swing.GroupLayout SubjectPanel4Layout = new javax.swing.GroupLayout(SubjectPanel4);
        SubjectPanel4.setLayout(SubjectPanel4Layout);
        SubjectPanel4Layout.setHorizontalGroup(
            SubjectPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SubjectPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SubjectPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane20)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE)
                    .addComponent(NewAssignmentButton4, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MarkLabel4, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        SubjectPanel4Layout.setVerticalGroup(
            SubjectPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SubjectPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(NewAssignmentButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(MarkLabel4)
                .addGap(11, 11, 11)
                .addComponent(jScrollPane20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane3.addTab("tab4", SubjectPanel4);

        UpcomingSubjectList5.setBorder(javax.swing.BorderFactory.createTitledBorder("RELATED UPCOMING ASSIGNMENTS"));
        UpcomingSubjectList5.setFont(new java.awt.Font("Candara", 1, 12)); // NOI18N
        UpcomingSubjectList5.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane9.setViewportView(UpcomingSubjectList5);

        NewAssignmentButton5.setFont(new java.awt.Font("Candara", 1, 12)); // NOI18N
        NewAssignmentButton5.setText("CREATE NEW ASSIGNMENT");

        MarkLabel5.setFont(new java.awt.Font("Candara", 1, 12)); // NOI18N
        MarkLabel5.setText("MARKS RECIEVED");

        MarkArea5.setColumns(20);
        MarkArea5.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        MarkArea5.setRows(5);
        MarkArea5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 2, true));
        jScrollPane21.setViewportView(MarkArea5);

        javax.swing.GroupLayout SubjectPanel5Layout = new javax.swing.GroupLayout(SubjectPanel5);
        SubjectPanel5.setLayout(SubjectPanel5Layout);
        SubjectPanel5Layout.setHorizontalGroup(
            SubjectPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SubjectPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SubjectPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane21)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE)
                    .addComponent(NewAssignmentButton5, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MarkLabel5, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        SubjectPanel5Layout.setVerticalGroup(
            SubjectPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SubjectPanel5Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(NewAssignmentButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(MarkLabel5)
                .addGap(11, 11, 11)
                .addComponent(jScrollPane21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane3.addTab("tab5", SubjectPanel5);

        UpcomingSubjectList6.setBorder(javax.swing.BorderFactory.createTitledBorder("RELATED UPCOMING ASSIGNMENTS"));
        UpcomingSubjectList6.setFont(new java.awt.Font("Candara", 1, 12)); // NOI18N
        UpcomingSubjectList6.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane10.setViewportView(UpcomingSubjectList6);

        NewAssignmentButton6.setFont(new java.awt.Font("Candara", 1, 12)); // NOI18N
        NewAssignmentButton6.setText("CREATE NEW ASSIGNMENT");

        MarkLabel6.setFont(new java.awt.Font("Candara", 1, 12)); // NOI18N
        MarkLabel6.setText("MARKS RECIEVED");

        MarkArea6.setColumns(20);
        MarkArea6.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        MarkArea6.setRows(5);
        MarkArea6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 2, true));
        jScrollPane22.setViewportView(MarkArea6);

        javax.swing.GroupLayout SubjectPanel6Layout = new javax.swing.GroupLayout(SubjectPanel6);
        SubjectPanel6.setLayout(SubjectPanel6Layout);
        SubjectPanel6Layout.setHorizontalGroup(
            SubjectPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SubjectPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SubjectPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane22)
                    .addComponent(jScrollPane10, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE)
                    .addComponent(NewAssignmentButton6, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MarkLabel6, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        SubjectPanel6Layout.setVerticalGroup(
            SubjectPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SubjectPanel6Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(NewAssignmentButton6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(MarkLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane3.addTab("tab6", SubjectPanel6);

        UpcomingSubjectList7.setBorder(javax.swing.BorderFactory.createTitledBorder("RELATED UPCOMING ASSIGNMENTS"));
        UpcomingSubjectList7.setFont(new java.awt.Font("Candara", 1, 12)); // NOI18N
        UpcomingSubjectList7.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane11.setViewportView(UpcomingSubjectList7);

        NewAssignmentButton7.setFont(new java.awt.Font("Candara", 1, 12)); // NOI18N
        NewAssignmentButton7.setText("CREATE NEW ASSIGNMENT");

        MarkLabel7.setFont(new java.awt.Font("Candara", 1, 12)); // NOI18N
        MarkLabel7.setText("MARKS RECIEVED");

        MarkArea7.setColumns(20);
        MarkArea7.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        MarkArea7.setRows(5);
        MarkArea7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 2, true));
        jScrollPane23.setViewportView(MarkArea7);

        javax.swing.GroupLayout SubjectPanel7Layout = new javax.swing.GroupLayout(SubjectPanel7);
        SubjectPanel7.setLayout(SubjectPanel7Layout);
        SubjectPanel7Layout.setHorizontalGroup(
            SubjectPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SubjectPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SubjectPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane23)
                    .addComponent(jScrollPane11, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE)
                    .addComponent(NewAssignmentButton7, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MarkLabel7, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        SubjectPanel7Layout.setVerticalGroup(
            SubjectPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SubjectPanel7Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(NewAssignmentButton7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(MarkLabel7)
                .addGap(11, 11, 11)
                .addComponent(jScrollPane23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane3.addTab("tab7", SubjectPanel7);

        AddSubjectButton.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        AddSubjectButton.setText("ADD SUBJECT");

        RemoveSubjectButton.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        RemoveSubjectButton.setText("REMOVE SUBJECT");

        javax.swing.GroupLayout SubjectPanelLayout = new javax.swing.GroupLayout(SubjectPanel);
        SubjectPanel.setLayout(SubjectPanelLayout);
        SubjectPanelLayout.setHorizontalGroup(
            SubjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SubjectPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SubjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SubjectsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(SubjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(RemoveSubjectButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(AddSubjectButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jTabbedPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(163, Short.MAX_VALUE))
        );
        SubjectPanelLayout.setVerticalGroup(
            SubjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SubjectPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SubjectsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jTabbedPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AddSubjectButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RemoveSubjectButton)
                .addContainerGap())
        );

        MainPane.addTab("SUBJECTS", SubjectPanel);

        TimeTablePanel.setBackground(new java.awt.Color(153, 204, 255));

        TimeTableLabel.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        TimeTableLabel.setText("TIMETABLE");

        TimeTable.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 204), 2, true));
        TimeTable.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        TimeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "MONDAY", "TUESDAY", "WEDNESDAY", "THURSDAY", "FRIDAY", "SATURDAY", "SUNDAY"
            }
        ));
        TimeTable.setColumnSelectionAllowed(true);
        jScrollPane3.setViewportView(TimeTable);
        TimeTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        AddEventButton.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        AddEventButton.setText("ADD EVENT");

        RemoveEventButton.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        RemoveEventButton.setText("REMOVE EVENT");

        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout TimeTablePanelLayout = new javax.swing.GroupLayout(TimeTablePanel);
        TimeTablePanel.setLayout(TimeTablePanelLayout);
        TimeTablePanelLayout.setHorizontalGroup(
            TimeTablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TimeTablePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TimeTablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TimeTablePanelLayout.createSequentialGroup()
                        .addComponent(TimeTableLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(488, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TimeTablePanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TimeTablePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AddEventButton)
                .addGap(52, 52, 52)
                .addComponent(RemoveEventButton)
                .addGap(222, 222, 222))
        );
        TimeTablePanelLayout.setVerticalGroup(
            TimeTablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TimeTablePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TimeTableLabel)
                .addGroup(TimeTablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TimeTablePanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(TimeTablePanelLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                .addGroup(TimeTablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RemoveEventButton)
                    .addComponent(AddEventButton))
                .addGap(93, 93, 93))
        );

        MainPane.addTab("TIMETABLE", TimeTablePanel);

        TermPanel.setBackground(new java.awt.Color(153, 204, 255));

        TermTable.setFont(new java.awt.Font("Candara", 1, 12)); // NOI18N
        TermTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "JAN", "FEB", "MAR", "APR", "MAY", "JUN", "JUL", "AUG", "SEP", "OCT", "NOV", "DEC"
            }
        ));
        jScrollPane4.setViewportView(TermTable);

        TermOverviewLabel.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        TermOverviewLabel.setText("TERM OVERVIEW");

        AddEventButton2.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        AddEventButton2.setText("ADD EVENT");

        DeleteEventButton.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        DeleteEventButton.setText("DELETE EVENT");

        javax.swing.GroupLayout TermPanelLayout = new javax.swing.GroupLayout(TermPanel);
        TermPanel.setLayout(TermPanelLayout);
        TermPanelLayout.setHorizontalGroup(
            TermPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TermPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TermPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 629, Short.MAX_VALUE)
                    .addGroup(TermPanelLayout.createSequentialGroup()
                        .addGroup(TermPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TermOverviewLabel)
                            .addGroup(TermPanelLayout.createSequentialGroup()
                                .addComponent(AddEventButton2)
                                .addGap(28, 28, 28)
                                .addComponent(DeleteEventButton)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        TermPanelLayout.setVerticalGroup(
            TermPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TermPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TermOverviewLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(TermPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddEventButton2)
                    .addComponent(DeleteEventButton))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        MainPane.addTab("TERM OVERVIEW", TermPanel);

        TasksDonePanel.setBackground(new java.awt.Color(153, 204, 255));

        CompletedList.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "COMPLETED: ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Candara", 1, 12), new java.awt.Color(153, 204, 255))); // NOI18N
        CompletedList.setFont(new java.awt.Font("Candara", 1, 12)); // NOI18N
        CompletedList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(CompletedList);

        TasksDoneLabel.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        TasksDoneLabel.setText("TASKS DONE ");

        ViewInfoButton2.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        ViewInfoButton2.setText("VIEW INFO");

        DeleteButton.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        DeleteButton.setText("DELETE");

        javax.swing.GroupLayout TasksDonePanelLayout = new javax.swing.GroupLayout(TasksDonePanel);
        TasksDonePanel.setLayout(TasksDonePanelLayout);
        TasksDonePanelLayout.setHorizontalGroup(
            TasksDonePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TasksDonePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TasksDonePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TasksDoneLabel)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(TasksDonePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(DeleteButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ViewInfoButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(213, Short.MAX_VALUE))
        );
        TasksDonePanelLayout.setVerticalGroup(
            TasksDonePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TasksDonePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TasksDoneLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ViewInfoButton2)
                .addGap(18, 18, 18)
                .addComponent(DeleteButton)
                .addContainerGap(95, Short.MAX_VALUE))
        );

        MainPane.addTab("TASKS DONE", TasksDonePanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddEventButton;
    private javax.swing.JButton AddEventButton2;
    private javax.swing.JButton AddSubjectButton;
    private javax.swing.JList<String> CompletedList;
    private javax.swing.JTextArea DateArea;
    private javax.swing.JLabel DateLabel;
    private javax.swing.JButton DeleteButton;
    private javax.swing.JButton DeleteEventButton;
    private javax.swing.JPanel HomePanel;
    private javax.swing.JTabbedPane MainPane;
    private javax.swing.JTextArea MarkArea1;
    private javax.swing.JTextArea MarkArea2;
    private javax.swing.JTextArea MarkArea3;
    private javax.swing.JTextArea MarkArea4;
    private javax.swing.JTextArea MarkArea5;
    private javax.swing.JTextArea MarkArea6;
    private javax.swing.JTextArea MarkArea7;
    private javax.swing.JButton MarkDoneButton;
    private javax.swing.JLabel MarkLabel1;
    private javax.swing.JLabel MarkLabel2;
    private javax.swing.JLabel MarkLabel3;
    private javax.swing.JLabel MarkLabel4;
    private javax.swing.JLabel MarkLabel5;
    private javax.swing.JLabel MarkLabel6;
    private javax.swing.JLabel MarkLabel7;
    private javax.swing.JButton NewAssigmentButton2;
    private javax.swing.JButton NewAssignmentButton1;
    private javax.swing.JButton NewAssignmentButton4;
    private javax.swing.JButton NewAssignmentButton5;
    private javax.swing.JButton NewAssignmentButton6;
    private javax.swing.JButton NewAssignmentButton7;
    private javax.swing.JButton RemoveEventButton;
    private javax.swing.JButton RemoveSubjectButton;
    private javax.swing.JPanel SubjectPanel;
    private javax.swing.JPanel SubjectPanel1;
    private javax.swing.JPanel SubjectPanel2;
    private javax.swing.JPanel SubjectPanel3;
    private javax.swing.JPanel SubjectPanel4;
    private javax.swing.JPanel SubjectPanel5;
    private javax.swing.JPanel SubjectPanel6;
    private javax.swing.JPanel SubjectPanel7;
    private javax.swing.JLabel SubjectsLabel;
    private javax.swing.JLabel TasksDoneLabel;
    private javax.swing.JPanel TasksDonePanel;
    private javax.swing.JLabel TermOverviewLabel;
    private javax.swing.JPanel TermPanel;
    private javax.swing.JTable TermTable;
    private javax.swing.JTable TimeTable;
    private javax.swing.JLabel TimeTableLabel;
    private javax.swing.JPanel TimeTablePanel;
    private javax.swing.JList<String> UpcomingAssignmentList;
    private javax.swing.JList<String> UpcomingSubjectList1;
    private javax.swing.JList<String> UpcomingSubjectList2;
    private javax.swing.JList<String> UpcomingSubjectList3;
    private javax.swing.JList<String> UpcomingSubjectList4;
    private javax.swing.JList<String> UpcomingSubjectList5;
    private javax.swing.JList<String> UpcomingSubjectList6;
    private javax.swing.JList<String> UpcomingSubjectList7;
    private javax.swing.JButton ViewInfoButton;
    private javax.swing.JButton ViewInfoButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane19;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane20;
    private javax.swing.JScrollPane jScrollPane21;
    private javax.swing.JScrollPane jScrollPane22;
    private javax.swing.JScrollPane jScrollPane23;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JLabel mainScreenLabel;
    private javax.swing.JButton newAssignmentButton3;
    // End of variables declaration//GEN-END:variables
}
